image:
  file: .gitpod.Dockerfile

tasks:
  - before: sh ./.gitpod/pgadmin4/setup-web-unattended.sh
    command: >
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && 
      psql --command "CREATE DATABASE cloudcode;" &&
      npm install &&
      npm run dev

ports:
  - port: 1337
    onOpen: open-browser
  - port: 5050
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
    visibility: private
