image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: > 
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && 
      psql --command "CREATE DATABASE parse;" && 
      sh ./.gitpod/setup-web-unattended.sh &&
      cp .env.example .env &&
      npm run dev

ports:
  - port: 1337
    onOpen: open-preview
  - port: 5050
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
