apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.port }}
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
